[tox]
envlist = py36,py37,py38,py39,pypy3
isolated_build = True

[tox:.package]
basepython = python3.9

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39
    pypy3: pypy3

[testenv]
deps=
    pytest>=6.2.2
    hypothesis>=6.1.1
    pytz>=2021.1
commands=py.test -vv --tb=short iso8601
setenv =
    LC_ALL=C
